export const DETAIL_DATA = "DETAIL_DATA";

// Auth
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_VERIFICATION_SUCCESS = "SIGNUP_VERIFICATION_SUCCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const FORGET_PASSWORD = "FORGET_PASSWORD";

// Loding View
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_VERIFICATION_LOADING = "SIGNUP_VERIFICATION_LOADING";
